<div class="grid grid-flow-row-dense grid-cols-2 gap-3 m-2" >


<p class="bg-red-300 first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar quam ac interdum ultrices. Nullam urna sapien, rhoncus sit amet placerat at, vestibulum et enim. Aliquam fringilla tincidunt egestas. Praesent quis odio neque. Nam nec malesuada lorem. Proin placerat lacus ut pellentesque finibus. Aliquam posuere felis in nisi pretium, in pulvinar odio sollicitudin. Fusce interdum metus vel quam lobortis auctor.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Sed blandit, nulla ac finibus imperdiet, tortor metus pellentesque dui, et placerat nisi purus non eros. Phasellus posuere leo lectus, id consequat tortor scelerisque id. Quisque vel dui risus. Vestibulum eu sem gravida, consectetur eros at, imperdiet lacus. Sed vehicula ante eu porttitor tincidunt. Praesent nec fermentum enim. Sed in pulvinar libero. Vestibulum tristique nisi eget nisl molestie aliquet. Maecenas non enim nisi. Fusce eu suscipit lectus. Nullam ac velit sapien. Praesent scelerisque augue vel mi molestie commodo.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left" >Ut in ornare urna, vitae placerat neque. Fusce ultricies nisl eget erat fringilla elementum. In sapien nunc, scelerisque non luctus eu, maximus in sem. Suspendisse potenti. Duis eu massa ultricies, tincidunt tortor ac, consequat tortor. Curabitur purus augue, consequat ut egestas sed, ornare nec mi. Maecenas feugiat sem a lacus bibendum commodo.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Vestibulum eget maximus augue, et imperdiet tellus. Aenean finibus tincidunt ligula eget suscipit. Ut gravida lectus et dolor ultrices viverra faucibus pellentesque dolor. Nam diam neque, placerat id egestas non, malesuada nec ipsum. Cras enim turpis, luctus et mauris ac, dapibus tincidunt felis. Suspendisse leo ligula, condimentum tincidunt orci eget, bibendum molestie nisi. Donec eleifend ipsum ac tortor viverra volutpat. Nulla placerat scelerisque dui nec fermentum. Duis lacus orci, fermentum ut porttitor non, vehicula nec ex. Donec mi elit, tincidunt rhoncus ullamcorper eu, bibendum ut quam. Sed condimentum risus porttitor lacus molestie dignissim. Aenean vestibulum, ligula in consequat volutpat, purus turpis tincidunt leo, at molestie dui velit id ipsum. Mauris mattis felis sapien, in ultrices est dignissim luctus. Nam ultricies ut augue id finibus. Nunc blandit risus maximus dictum bibendum. Pellentesque molestie, leo et ultricies ultrices, justo magna vulputate velit, sit amet mattis mauris lectus fermentum libero.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">In velit quam, feugiat eget maximus in, ultrices commodo elit. Curabitur sed volutpat sem. Nam convallis eget nisl sit amet maximus. Curabitur hendrerit mauris in odio maximus, at suscipit ex euismod. Morbi rutrum aliquam mauris non facilisis. Ut sed odio vitae lorem ullamcorper lobortis non in dui. Integer dapibus tincidunt consectetur. Donec vitae laoreet urna. Vivamus nunc risus, rutrum non vestibulum quis, mollis sit amet dui. Integer non ultricies libero. Nulla diam tellus, sollicitudin sed massa sit amet, eleifend vulputate eros. Fusce ut orci et purus tempor facilisis. Nulla tincidunt in risus in iaculis. Phasellus dictum, sapien vel interdum sollicitudin, enim dolor sodales lacus, et dignissim felis magna eu augue.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Phasellus faucibus blandit lectus sed pharetra. Cras iaculis velit eu quam gravida, eget condimentum nunc tincidunt. Aenean scelerisque ante at luctus laoreet. Sed sit amet congue orci. Nulla ac arcu lorem. Suspendisse mattis enim metus, sit amet viverra est blandit quis. Duis accumsan porta nulla luctus molestie. Cras lobortis odio nisl, consectetur consectetur massa aliquet et. Curabitur in ultrices elit, nec lobortis erat. Curabitur sapien nunc, feugiat at gravida sed, accumsan eget arcu. Ut in lacus arcu.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Pellentesque id erat lacinia, pellentesque libero a, semper tellus. Aenean maximus leo at turpis efficitur viverra. Vestibulum semper, urna et molestie sagittis, purus turpis condimentum velit, finibus tempus sem purus porttitor eros. Duis vitae quam eget lorem rutrum consectetur. Vivamus vel velit id augue imperdiet tempus. Ut eget urna non augue posuere varius. Curabitur venenatis justo lorem, vehicula suscipit ipsum feugiat sed. Cras vel porta odio. Sed placerat dolor tellus, non tincidunt felis varius in. Etiam ac diam ultricies, viverra libero eu, tempus dolor. Nam eu gravida neque, vulputate mollis ante. Sed dui dolor, cursus non diam ut, volutpat hendrerit lorem. Pellentesque sed neque non ipsum rutrum lobortis. Aliquam scelerisque sem eu suscipit blandit.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Phasellus pretium facilisis lorem eget blandit. Vestibulum odio odio, pellentesque id finibus sodales, hendrerit in ligula. In hac habitasse platea dictumst. Morbi interdum urna nec nisl aliquet, sed dictum libero semper. Nunc sit amet est vehicula, lacinia massa et, sagittis risus. Suspendisse nec justo vitae sem lobortis tristique. Vestibulum malesuada, ligula at bibendum scelerisque, eros lectus lobortis ante, nec sollicitudin nisi sapien varius est. Phasellus vulputate pharetra lobortis. In leo quam, vulputate et augue sit amet, imperdiet gravida arcu. Quisque sagittis ornare elit quis efficitur. Mauris efficitur sagittis nunc venenatis lobortis. Praesent tincidunt, sapien non iaculis tempus, justo velit interdum metus, a ornare purus massa tempor massa.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Cras congue libero urna, a sodales nisi venenatis vitae. Pellentesque sollicitudin laoreet sagittis. Duis ullamcorper ut libero sit amet fermentum. Donec luctus odio eget nisl cursus mollis. Maecenas eget nulla turpis. Donec vestibulum ornare mi, vitae sodales mauris dictum in. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Morbi pulvinar sollicitudin finibus. Suspendisse quis feugiat mauris. Maecenas faucibus fermentum finibus. Morbi ut lectus vel ante pretium consequat sit amet eu quam. Mauris gravida tortor at augue pretium, in dapibus dui congue. Donec sed arcu libero. Nullam luctus, massa vel porttitor sodales, metus elit mollis tortor, quis dictum tellus quam ac arcu. Vestibulum euismod odio et imperdiet semper. Morbi malesuada eu dui eget rutrum. Etiam eget est nec est rhoncus scelerisque. Sed in purus nec nisi pretium efficitur eu et leo. </p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Cras congue libero urna, a sodales nisi venenatis vitae. Pellentesque sollicitudin laoreet sagittis. Duis ullamcorper ut libero sit amet fermentum. Donec luctus odio eget nisl cursus mollis. Maecenas eget nulla turpis. Donec vestibulum ornare mi, vitae sodales mauris dictum in. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>

<p class="first-letter:text-5xl first-letter:font-bold first-letter:mr-3 first-letter:float-left">Phasellus pretium facilisis lorem eget blandit. Vestibulum odio odio, pellentesque id finibus sodales, hendrerit in ligula. In hac habitasse platea dictumst. Morbi interdum urna nec nisl aliquet, sed dictum libero semper. Nunc sit amet est vehicula, lacinia massa et, sagittis risus. Suspendisse nec justo vitae sem lobortis tristique. Vestibulum malesuada, ligula at bibendum scelerisque, eros lectus lobortis ante, nec sollicitudin nisi sapien varius est. Phasellus vulputate pharetra lobortis. In leo quam, vulputate et augue sit amet, imperdiet gravida arcu. Quisque sagittis ornare elit quis efficitur. Mauris efficitur sagittis nunc venenatis lobortis. Praesent tincidunt, sapien non iaculis tempus, justo velit interdum metus, a ornare purus massa tempor massa.</p>

</div>